"""Verifier Agent — the final gate before output.

Runs deterministic checks (source integrity/freshness, calculation consistency,
budget-gap re-derivation, plausibility bands) and produces a pass/warn/fail report.
A short human-readable summary is generated by the LLM when available, else a
deterministic fallback. Failures are surfaced, never hidden.
"""
from __future__ import annotations

from datetime import date

from dateutil.relativedelta import relativedelta

from app.agents.context import PlanningContext
from app.core.config import settings
from app.core.llm_client import llm
from app.core.schemas import VerificationCheck, VerificationReport

TOLERANCE = 1.0  # report-currency units
LIVING_BAND = (80.0, 6000.0)     # plausible monthly living
TUITION_BAND = (0.0, 60000.0)    # plausible annual tuition


def _worst(statuses: list[str]) -> str:
    if "fail" in statuses:
        return "fail"
    if "warn" in statuses:
        return "warn"
    return "pass"


class VerifierAgent:
    name = "verifier"

    def run(self, ctx: PlanningContext) -> None:
        checks: list[VerificationCheck] = []
        checks.append(self._source_integrity(ctx))
        checks.append(self._source_freshness(ctx))
        checks.append(self._totals_consistency(ctx))
        checks.append(self._budget_gap(ctx))
        checks.append(self._plausibility(ctx))
        checks.append(self._scholarships(ctx))

        overall = _worst([c.status for c in checks])
        report = VerificationReport(overall=overall, checks=checks)
        report.summary = self._summary(report)
        ctx.verification = report

    def _source_integrity(self, ctx: PlanningContext) -> VerificationCheck:
        missing = [
            ln.label
            for plan in ctx.candidates
            for ln in plan.lines
            if ln.confidence == "sourced" and not ln.citation.url
        ]
        if missing:
            return VerificationCheck(
                name="source_integrity", status="fail",
                detail=f"{len(missing)} 'sourced' figures lack a source URL: {sorted(set(missing))}",
            )
        return VerificationCheck(
            name="source_integrity", status="pass",
            detail="Every 'sourced' figure has a source URL; estimates are labelled.",
        )

    def _source_freshness(self, ctx: PlanningContext) -> VerificationCheck:
        cutoff = date.today() - relativedelta(months=settings.source_stale_months)
        stale = {
            ln.citation.publisher
            for plan in ctx.candidates
            for ln in plan.lines
            if ln.citation.accessed_date and ln.citation.accessed_date < cutoff
        }
        if stale:
            return VerificationCheck(
                name="source_freshness", status="warn",
                detail=f"Sources older than {settings.source_stale_months} months: {sorted(stale)}",
            )
        return VerificationCheck(
            name="source_freshness", status="pass",
            detail=f"All sources accessed within {settings.source_stale_months} months.",
        )

    def _totals_consistency(self, ctx: PlanningContext) -> VerificationCheck:
        for plan in ctx.candidates:
            recomputed = round(sum(ln.amount for ln in plan.lines), 2)
            if abs(recomputed - plan.total_annual) > TOLERANCE:
                return VerificationCheck(
                    name="totals_consistency", status="fail",
                    detail=(
                        f"{plan.university_name}: line sum {recomputed} != total "
                        f"{plan.total_annual}"
                    ),
                )
            if plan.total_annual < 0:
                return VerificationCheck(
                    name="totals_consistency", status="fail",
                    detail=f"{plan.university_name}: negative total {plan.total_annual}",
                )
        return VerificationCheck(
            name="totals_consistency", status="pass",
            detail="Each total equals the sum of its (annualized) components; no negatives.",
        )

    def _budget_gap(self, ctx: PlanningContext) -> VerificationCheck:
        if ctx.budget_in_report is None:
            return VerificationCheck(name="budget_gap", status="warn", detail="Budget not converted.")
        for plan in ctx.candidates:
            expected = round(ctx.budget_in_report - plan.total_annual, 2)
            if plan.budget_gap is None or abs(expected - plan.budget_gap) > TOLERANCE:
                return VerificationCheck(
                    name="budget_gap", status="fail",
                    detail=f"{plan.university_name}: gap {plan.budget_gap} != budget-total {expected}",
                )
        return VerificationCheck(
            name="budget_gap", status="pass",
            detail="Budget gaps equal budget minus total for every candidate.",
        )

    def _plausibility(self, ctx: PlanningContext) -> VerificationCheck:
        issues: list[str] = []
        for plan in ctx.candidates:
            if not (LIVING_BAND[0] <= plan.monthly_living <= LIVING_BAND[1]):
                issues.append(f"{plan.city_name} living {plan.monthly_living:.0f}/mo out of band")
            if not (TUITION_BAND[0] <= plan.annual_tuition <= TUITION_BAND[1]):
                issues.append(f"{plan.university_name} tuition {plan.annual_tuition:.0f}/yr out of band")
        if issues:
            return VerificationCheck(name="plausibility", status="warn", detail="; ".join(issues))
        return VerificationCheck(
            name="plausibility", status="pass",
            detail="Living and tuition figures fall within plausible ranges.",
        )

    def _scholarships(self, ctx: PlanningContext) -> VerificationCheck:
        matches = [m for plan in ctx.candidates for m in plan.scholarships]
        if not matches:
            return VerificationCheck(
                name="scholarships", status="pass",
                detail="No scholarships in scope for these candidates.",
            )
        # Every surfaced award must be cited.
        uncited = sorted({m.name for m in matches if not m.citation.url})
        if uncited:
            return VerificationCheck(
                name="scholarships", status="fail",
                detail=f"Scholarships lacking a source URL: {uncited}",
            )
        issues: list[str] = []
        # Net total must never exceed gross, nor go negative.
        for plan in ctx.candidates:
            if plan.net_total_annual is not None and (
                plan.net_total_annual < 0 or plan.net_total_annual > plan.total_annual + TOLERANCE
            ):
                issues.append(f"{plan.university_name}: net {plan.net_total_annual} vs gross {plan.total_annual}")
        # Eligible/likely awards whose deadline has already passed.
        passed = sorted({
            m.name for m in matches
            if m.eligibility in ("eligible", "likely")
            and m.days_until_deadline is not None and m.days_until_deadline < 0
        })
        if passed:
            issues.append(f"deadline passed for: {passed}")
        if issues:
            return VerificationCheck(name="scholarships", status="warn", detail="; ".join(issues))
        return VerificationCheck(
            name="scholarships", status="pass",
            detail="Awards are cited; net totals consistent; no eligible deadline has passed.",
        )

    def _summary(self, report: VerificationReport) -> str:
        passed = sum(c.status == "pass" for c in report.checks)
        base = f"{passed}/{len(report.checks)} checks passed; overall: {report.overall}."
        if not llm.enabled:
            return base
        detail = "\n".join(f"- {c.name}: {c.status} — {c.detail}" for c in report.checks)
        text = llm.complete_text(
            system="You are a verification assistant. Summarize data-quality checks for a "
            "student cost report in 1-2 plain sentences. Be factual, no new numbers.",
            user=f"Overall: {report.overall}\n{detail}",
        )
        return text or base
